name: Bug
description: Something is wrong in the local runtime.
title: "bug: "
labels:
  - bug
body:
  - type: dropdown
    id: os
    attributes:
      label: OS
      description: Where you ran the handler.
      options:
        - Linux (Ubuntu, Debian, etc.)
        - macOS
        - Windows
        - more than one
        - not sure
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual
      description: What happened during the run, describe the error message or unexpected behavior.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expectation
      description: What is your expectation, what should have happened instead?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction details
      description: Procedure to reproduce the bug, if possible. Include commands, OS, Docker version if relevant.
    validations:
      required: true
